spring:
  application:
    name: concurrency-issue
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:53306/stock_example?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    # Lock ?? ? DB ?? ??? ?? ??? ? ???? default(10)?? ???? ???
    hikari:
      maximum-pool-size: 30

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE